### ISSUE TITLE
Excessive `console.log()` causes browser to crash

### ISSUE THREAD

**Issue by awulkan** [vuejs/devtools#1575] opened 2021-09-30 12:26 UTC
### Version
6.0.0-beta.18

### Browser and OS info
Edge Version 94.0.992.31 (Official build) (64-bit)

### Steps to reproduce
I have a Vue 3 project that uses PrimeVue as a component library. Whenever I type anything into the search filter in a DataTable component (https://primefaces.org/primevue/showcase/#/datatable/filter), the Vue DevTools extension logs hundreds of things to my console. This causes the whole tab to freeze or crash.

The logging that's causing the crash is in the "backend.js" file.
```js
/**
 * Process the props of an instance.
 * Make sure return a plain object because window.postMessage()
 * will throw an Error if the passed object contains Functions.
 *
 * @param {Vue} instance
 * @return {Array}
 */
function processProps(instance) {
    var propsData = [];
    var propDefinitions = instance.type.props;
    var loop = function ( key ) {
        var propDefinition = propDefinitions ? propDefinitions[key] : null;
        console.log(key, propDefinition);
        key = shared_utils_1.camelize(key);
        propsData.push({
            type: 'props',
            key,
            value: util_2.returnError(() => instance.props[key]),
            meta: propDefinition
                ? Object.assign({}, {type: propDefinition.type ? getPropType(propDefinition.type) : 'any',
                    required: !!propDefinition.required},
                    propDefinition.default != null
                        ? {
                            default: propDefinition.default.toString()
                        }
                        : {})
                : {
                    type: 'invalid'
                },
            editable: shared_data_1.default.editableProps
        });
    };

    for (var key in instance.props) loop( key );
    return propsData;
}
```

### What is expected?
No logs.

### What is actually happening?
So many logs that it crashes the tab.

**Comment by awulkan** [comment] 2021-09-30 15:09
I don't know how to reproduce this bug. It happens sporadically, and restarting Edge appears to fix it. I've only encountered when working with PrimeVue though.

**Comment by Akryum** [comment] 2021-09-30 19:32
Duplicate of #1567

**Closed by Akryum** 2021-09-30 19:32 UTC
