### ISSUE TITLE
Can't expand all components since latest update 6.0.0 beta 17

### ISSUE THREAD

**Issue by kieranbarlow** [vuejs/devtools#1563] opened 2021-09-21 12:17 UTC
### Version
6.0.0-beta.17

### Browser and OS info
Chrome 93 / MacOS 11.4

### Steps to reproduce
- Load vue project
- Inspect vue project via chrome 
- Try expanding components

It appears to be any components loaded within 
`<component v-bind:is="layout"></component>`

### What is expected?
Components should expand

### What is actually happening?
Components don't expand

---
Opened chrome as usual to continue and since the update, I can no longer expand components.

**Comment by Jurool** [comment] 2021-09-22 06:34
me too.
chrome 93.0.4577.63 / window 10

**Comment by chris-garner** [comment] 2021-09-23 07:29
Me too! Would love a fix ASAP :)
Chrome 94.0.4606.54 (Official Build) (x86_64) / macOS 11.5.2

**Comment by horsthacker** [comment] 2021-09-24 08:21
Me too
Version 94.0.4606.61 (Offizieller Build) (64-Bit) / Windows 10

**Comment by arashm** [comment] 2021-09-24 13:27
Have the same problem in Firefox and `6.0.0.beta.18`.

**Comment by TDola** [comment] 2021-09-28 18:27
Same in Electron 8.5.5 and newer.  Still happening in 13.4.0.  Desperately need fix for debugging extremely large application

**Comment by chris-garner** [comment] 2021-09-29 09:00
To add more context - this seems to be affecting any components loaded though `<component>` **OR** those using a render function. For me, the beta devtool is useless until this is fixed. Thankfully, the non-beta version still allows inspection of all components.

**Comment by Akryum** [comment] 2021-09-29 09:53
Duplicate of #1560

**Closed** 2021-09-29 09:53 UTC
