### ISSUE TITLE
sub is not a function

### ISSUE THREAD

**Issue by sabist** [vuejs/devtools#1897] opened 2022-06-27 12:07 UTC
### Version
6.1.4

### Browser and OS info
firefox 101.0.1 / Windows 10

### Steps to reproduce
1- in mounted hook this.$store.dispatch is called (dispatch successfully)
2- route change
3- go back to the same first route
4- error shows (sub is not a function)

### What is expected?
this.$store.dispatch dispatches when no error

### What is actually happening?
error : sub is not a function

---
i am using nuxt 2.15.8 but it have nothing to do with that
the problem is on the vuex

**Comment by Akryum** [comment] 2022-06-27 12:10
Duplicate of #1728

**Closed by Akryum** 2022-06-27 12:10 UTC
