### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'instanceMap')

### ISSUE THREAD

**Issue by shengwei-sam** [vuejs/devtools#1928] opened 2022-08-05 08:05 UTC
### Version
6.2.1

### Browser and OS info
Google Chrome 104.0.5112.81

![image](https://user-images.githubusercontent.com/41235576/183030236-3fc94ea2-eba6-449a-bc70-751795d30b00.png)

### Steps to reproduce
Just open console

### What is expected?
No error

### What is actually happening?
TypeError: Cannot read properties of null (reading 'instanceMap')

**Comment by Akryum** [comment] 2022-09-24 22:53
Duplicate of #1892

**Closed by Akryum** 2022-09-24 22:53 UTC
