### ISSUE TITLE
Collapse all properties

### ISSUE THREAD

**Issue by debug87** [vuejs/devtools#1543] opened 2021-08-19 08:35 UTC
Why are all (or some) properties always expanded? It is incredibly annoying when everything is expanded every time and you have to collapse it to get a clear view.
All properties (data, props, etc.) should always be collapsed.

**Comment by piotrmachacki** [comment] 2021-12-10 07:01
Please fix this because it's currently hard to use when everything is expanded.

**Comment by konpeki622** [comment] 2021-12-13 08:55
For collapse all properties, press `ctrl` or `meta` on keyboard while clicking the toggle. For expand press `shift` instead.

**Comment by Akryum** [comment] 2022-09-24 22:54
Duplicate of #1391

**Closed by Akryum** 2022-09-24 22:54 UTC
