### ISSUE TITLE
Uncaught (in promise) TypeError: sub is not a function

### ISSUE THREAD

**Issue by jdmoraless** [vuejs/devtools#1853] opened 2022-05-03 17:56 UTC
### Version
6.1.4

### Browser and OS info
Firefox Version 99.0, Ubuntu 20.04

### Steps to reproduce
1. Activate the Vue devTools (6.1.4)
2. Open the browser console
3. And appears the Uncaught (in promise) TypeError: sub is not a function. The screenshot: https://i.imgur.com/DP02fS5.png

### What is expected?
I expect that load all without problems.

### What is actually happening?
The web application don't load only it's working if disable the dev-tools from the browser.

---
I would like to choose  keep the previous version of Vue devTools, because the upgrade to the new version is forced and stop all process of development :(

**Comment by Akryum** [comment] 2022-05-03 20:58
Duplicate of #1686

**Comment by Akryum** [comment] 2022-05-03 20:58
> I would like to choose keep the previous version of Vue devTools, because the upgrade to the new version is forced and stop all process of development :(

Read the docs 😉

**Closed by Akryum** 2022-05-03 20:58 UTC
