### ISSUE TITLE
 Cannot read properties of undefined (reading 'substr')  - backend.js:949:57

### ISSUE THREAD

**Issue by polPintero** [vuejs/devtools#1689] opened 2022-02-09 10:30 UTC
### Version
6.0.0

### Reproduction link
[http://localhost:8881/](http://localhost:8881/)
Error in this line:
 const baseFrameworkVersion = parseInt(options.version.substr(0, options.version.indexOf('.')));

### Steps to reproduce
Vue 2. Open vue-devtools in chrome

### What is expected?
no error

### What is actually happening?
error

**Comment by Akryum** [comment] 2022-02-09 10:54
Duplicate of #1687

**Closed by Akryum** 2022-02-09 10:54 UTC
