### ISSUE TITLE
component selection tool not working

### ISSUE THREAD

**Issue by ali2966** [vuejs/devtools#2143] opened 2024-03-02 07:16 UTC
### Vue devtools version

6.6.1

### Link to minimal reproduction

None

### Steps to reproduce & screenshots

click on component selection tool, try to inspect any component, it doesn't work.
after closing and opening up the devtools, it will work.

### What is expected?

component being selected

### What is actually happening?

component not being selected

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04 LTS 22.04 (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 10.15 GB / 19.41 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
  Browsers:
    Chrome: 115.0.5790.110
```

### Any additional comments?

also, sometimes the devtools freezes and stops working

**Comment by Parsa361** [comment] 2024-03-02 08:19
I have the same problem, I wonder why no one mentioned it in these two weeks

**Comment by taigabrew** [comment] 2024-03-06 08:15
Same problem.
Component selection isn't working after hot reload. Personaly saw this with Webpack and Vite.
This behaviour started to appear after DevTools major update.

**Comment by jiikoosol** [comment] 2024-03-08 08:47
I have the same problem. Hot reload in some way "freezes" the Vue devtools and requires closing and reopening Chrome's dev-tools, and page refresh after that.

Chrome 122.0.6261.112 / MacOS 14.3.1 / Vite 4.5.2

**Comment by gregveres** [comment] 2024-03-12 15:18
I am seeing the same problem. I have to close the debugger and start the debugger again.
I am using vue 2.7 with webpack 4. Oh, I can't wait to be able to move to vue 3 and vite.

**Comment by june07** [comment] 2024-03-19 17:26
> I am seeing the same problem. I have to close the debugger and start the debugger again. I am using vue 2.7 with webpack 4. Oh, I can't wait to be able to move to vue 3 and vite.

Unfortunately, the same persists with Vue 3 and Vite!
me: Vue 3.4.21, Vite 5.0.11

**Comment by idoomguy** [comment] 2024-03-21 15:20
I have exact same problem, after the last major devtools update.

**Comment by n4ks** [comment] 2024-03-29 09:40
Same problem for a long time

**Comment by 0x2c9** [comment] 2024-03-29 23:56
Since the update the devtools are barely usable, every HMR breaks the vue-devtools and only become usable again after the browser devtools are reopened. 

In my case Nuxt v3.11.1 / Vue 3.2.21

**Comment by VanillaTank** [comment] 2024-04-03 06:20
Same problem for a long time, Chrome

**Comment by taylordragoo** [comment] 2024-04-08 15:43
I get the same issue using Chrome and Firefox on macOS. Luckily on Chrome I can right-click and select 'Reload Frame' which reloads the devtools window and the components are updated as expected. As far as I'm aware Firefox does not have the ability to reload the devtool frame and therefore you must close the devtools window and re-open it.

**Comment by DenisTHEVENOT** [comment] 2024-05-28 12:50
+1 same problem.
@taylordragoo thanks for the hack 👍

**Comment by Akryum** [comment] 2024-06-06 14:50
Is this still an issue with 6.6.3?

**Comment by gregveres** [comment] 2024-06-06 15:57
@Akryum I just tried to reproduce this using 6.6.3 and component selection was happening properly every time, including after several HMRs.

So I would say that 6.6.3 fixed. Very much appreciated!

**Closed** 2024-06-06 16:12 UTC

**Comment by gregveres** [comment] 2024-06-24 16:15
@taylordragoo this issue was for the component selection not working. DevTools still locks up for me on 6.6.3 too, but I have not had a situation where component selection stopped working when DevTools was not locked up. The locking up is another issue in Github.

Also, in case you didn't see the "work around", you can right click on the DevTools window and say "Reload frame" and have DevTools come back to life.
