### ISSUE TITLE
DevTools becomes useless as soon as I refresh the page

### ISSUE THREAD

**Issue by rahulmeghlan** [vuejs/devtools#1725] opened 2022-02-12 16:51 UTC
### Version
6.0.8

### Browser and OS info
Chrome: Version 98.0.4758.80/ Mac: Version 12.1

### Steps to reproduce
Whenever I refresh the page the Vue devtools becomes completely unusable, i.e don't see any of my components/ vuex store etc.

### What is expected?
DevTools should work fine even after page reload

### What is actually happening?
DevTools stop working on page-refresh

**Comment by rahulmeghlan** [comment] 2022-02-12 16:52
Getting the following error on console:

backend.js:2205 Uncaught TypeError: Cannot read properties of null (reading 'instanceMap')
    at Bridge.<anonymous> (backend.js:2205:55)
    at Bridge.emit (backend.js:9922:5)
    at Bridge._emit (backend.js:6557:12)
    at backend.js:6483:42
    at Array.forEach (<anonymous>)
    at backend.js:6483:18
    at listener (backend.js:13476:13)

**Comment by Akryum** [comment] 2022-02-13 12:55
Duplicate of #1711

**Closed by Akryum** 2022-02-13 12:55 UTC
