### ISSUE TITLE
Time Travel Debugging missing or not working

### ISSUE THREAD

**Issue by amcsi** [vuejs/devtools#1836] opened 2022-04-13 19:09 UTC
### Version
6.1.4

### Browser and OS info
Chrome 100, Ubuntu 20.04

### Steps to reproduce
You can skip steps 1-4 by just cloning this example project, running yarn install, then running yarn serve: https://github.com/amcsi/demonstrate-time-travel-not-working

In a Vue 2 app with Vuex:

1. go to the Vue DevTools
2. go to Timeline
3. go to Vuex Mutations
4. trigger Vuex mutations in your app if you haven't done so already
5. try to time-travel debug using the mutations list in DevTools

### What is expected?
Either: when hovering over a row, it should offer you a button to time travel to that mutation; or on double-click it should time-travel to that point in time with mutations.

Here is a video of an older version of Devtools and how hovering over each row offers you a bunch of buttons related to time-travel debugging (Commit, Revert, Time-Travel): https://user-images.githubusercontent.com/49567934/136670141-9cf404ff-50eb-4e3a-a87f-e8ef30d88724.gif

### What is actually happening?
It doesn't offer a time travel button, also, double-clicking on a mutation results in that row getting set as "selected", but that doesn't seem to do anything, and time travel is not happening.

---
🎥 Here is a link to a video demonstrating how Time Travel debugging isn't working using the example project mentioned above:

https://www.dropbox.com/s/b93a52n889qqt56/2022-04-13%2021-05-15.mp4?dl=0

**Comment by Akryum** [comment] 2022-04-13 19:21
Duplicate of https://github.com/vuejs/devtools/discussions/1692

**Closed by Akryum** 2022-04-13 19:21 UTC
