### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by Phil-jci** [vuejs/devtools#1642] opened 2021-12-20 15:57 UTC
### Version
6.0.0-beta.21

### Browser and OS info
Chrome 96 / Windows 11

### Steps to reproduce
Create a new project which includes vue-router with the @vue/cli.

Run the @vue/cli script 'serve' (npm run serve) from within the new project directory.

### What is expected?
Project builds and webpage is served at localhost.

### What is actually happening?
ERROR  Failed to compile with 1 error                                                                          15:27:04
 error  in ./node_modules/@vue/devtools-api/lib/esm/proxy.js

Module parse failed: Unexpected token (3:10)

---
I'm something of a noob when it comes to Vue and JS in general, but the problem suddenly appeared a few hours ago, which I noticed is when you releases version 6.0.0-beta.21. If I use npm to manually roll back the vue-devtools version to 6.0.0-beta.20.1 the script builds the files without issue.

**Comment by randomailer** [comment] 2021-12-20 16:03
for me the same situation

**Comment by leolivier** [comment] 2021-12-20 16:33
same issue for me

**Comment by kyrsquir** [comment] 2021-12-20 17:01
Adding this to `package.json` helped me as a temporary solution (installation of the older version didn't help as both `vue-router` and `vuex` depend on `@vue/devtools-api`):
```
"resolutions": {
  "@vue/devtools-api": "6.0.0-beta.20.1"
}
```

This only works with yarn though

**Comment by Akryum** [comment] 2021-12-20 18:45
Duplicate of #1641

**Closed by Akryum** 2021-12-20 18:45 UTC
