### ISSUE TITLE
Vue devtools crashes chrome

### ISSUE THREAD

**Issue by shezhangzhang** [vuejs/devtools#2134] opened 2024-01-29 06:47 UTC
### Vue devtools version

latest

### Link to minimal reproduction

.

### Steps to reproduce & screenshots

when you open it with a vue2 project, it will crashes chrome, which is unacceptable.

### What is expected?

ok

### What is actually happening?

chrome crash

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 6.56 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
    bun: 1.0.1 - ~/.bun/bin/bun
    Watchman: 2023.10.23.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
```

**Comment by borisovdev** [comment] 2024-01-31 11:26
Could it be related?
- https://github.com/vuejs/devtools/issues/2103

**Comment by altescape** [comment] 2024-02-20 17:01
Sounds similar to what I'm seeing - left a comment also on https://github.com/vuejs/devtools/issues/2103

**Comment by Akryum** [comment] 2024-02-20 17:48
Duplicate of #2103

**Closed by Akryum** 2024-02-20 17:48 UTC
