### ISSUE TITLE
Doesn't play well with vuex-persistedstate

### ISSUE THREAD

**Issue by watzon** [vuejs/devtools#1547] opened 2021-09-01 18:38 UTC
### Version
6.0.0-beta.15

### Browser and OS info
Firefox 91.0.1 on MacOS

### Steps to reproduce
1) Install vuex-persistedstate with the latest Vue Devtools beta.

2) Set some initial state for the store, doesn't matter what it is.

3) Use a mutation to modify the state.

4) Check the state in Vue Devtools, it should show as having been manipulated.

5) Refresh the browser. The state in Vue Devtools should show the default state without any of the changes.

### What is expected?
The state according to Vue Devtools should maintain across refreshes.

### What is actually happening?
The state is persisted as expected, but Vue Devtools shows the default state after a refresh.

---
I know this could also be an issue with the 3rd party library, but seeing as the library is working as expected and Vue Devtools is not I figured I'd file an issue here. The state is persisting across refreshes, but you can't see any of those changes in Vue Devtools. The one exception is when using getters. For some reason getters update as expected and are persisted.

**Comment by Akryum** [comment] 2021-09-01 20:55
Duplicate of the issue in vuejs/vuex

**Closed by Akryum** 2021-09-01 20:55 UTC

**Comment by watzon** [comment] 2021-09-01 21:32
@Akryum would you mind linking to the relevant issue?

**Comment by Akryum** [comment] 2021-09-01 21:58
https://github.com/vuejs/vuex/issues/2046
